services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "7001:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  bot:
    build:
      context: .
    container_name: bot
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - internal
    volumes:
      - ./i18n:/bot/i18n
    command: ["python", "-u", "run.py"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M

  redis:
    image: redis:7-alpine
    container_name: redis
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 100mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    networks:
      - internal
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M

volumes:
  redis_data:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
