services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always

  bot:
    build:
      context: .
    container_name: AiogramShopBot
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - caddy
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./i18n:/bot/i18n
    command: ["python", "-u", "run.py"]
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - caddy

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - caddy
    restart: always

volumes:
  redis_data:
  postgres_data:

networks:
  caddy:
